language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/codecept run
